# Generated by Django 5.1 on 2024-10-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('internal_phone', models.CharField(blank=True, max_length=10, verbose_name='Внутренний телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
