# Generated by Django 5.1 on 2024-10-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('internal_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон внутренний')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон мобильный')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Фото профиля')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата устройства в компанию')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Фото профиля')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='Дата устройства')),
                ('is_store_account', models.BooleanField(default=False, verbose_name='Учетная запись магазина')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_from_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
