# Generated by Django 5.1 on 2024-10-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Офис', 'Офис'), ('Склад', 'Склад'), ('Магазин', 'Магазин')], default='Офис', max_length=50)),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата устройства в компанию')),
                ('phone_number_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Мобильный телефон')),
                ('phone_number_internal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Внутренний телефон')),
                ('telegram_chat_ID', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID')),
                ('is_store_account', models.BooleanField(default=False)),
                ('can_post_news', models.BooleanField(default=False, verbose_name='Разрешить постить новости')),
                ('can_edit_news', models.BooleanField(default=False, verbose_name='Разрешить редактировать новости')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
