# Generated by Django 5.1 on 2024-10-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_statistics',
            field=models.BooleanField(default=False, verbose_name='Полная статистика'),
        ),
    ]
