# Generated by Django 5.1 on 2024-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='is_visible_for_office',
            field=models.BooleanField(default=False, verbose_name='для Офиса'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_visible_for_store',
            field=models.BooleanField(default=False, verbose_name='для Магазина'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='is_visible_for_warehouse',
            field=models.BooleanField(default=False, verbose_name='для Склада'),
        ),
    ]
