# Generated by Django 5.1 on 2024-11-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateField()),
                ('activity_time', models.TimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(related_name='activities', to='profiles.userprofile')),
            ],
        ),
    ]
