# Generated by Django 5.1 on 2024-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
