# Generated by Django 5.1 on 2024-10-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('tasks', '0001_initial'),
        ('users', '0002_userprofile_full_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='observer',
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='task',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='task_observers', to='users.userprofile', verbose_name='Наблюдатели'),
        ),
    ]
