# Generated by Django 5.1 on 2024-10-09 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_department_remove_task_observers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='observer',
        ),
        migrations.AddField(
            model_name='task',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели'),
        ),
    ]
