# Generated by Django 5.1 on 2024-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_observers_task_observer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('done', 'Завершенный'), ('early_completed', 'Завершена досрочно'), ('approval_pending', 'В процессе одобрения'), ('extension_requested', 'Запрошено продление'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус задачи'),
        ),
    ]
