# Generated by Django 5.1 on 2024-10-08 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('tectasks', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('task', models.ForeignKey(blank=True, help_text='Задача, к которой назначен наблюдатель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_observers', to='tasks.task', verbose_name='Задача')),
                ('tectask', models.ForeignKey(blank=True, help_text='Текущая задача, к которой назначен наблюдатель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tectask_observers', to='tectasks.tectask', verbose_name='Текущая задача')),
                ('ticket', models.ForeignKey(blank=True, help_text='Заявка, к которой назначен наблюдатель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_observers', to='tickets.ticket', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-наблюдатель')),
            ],
            options={
                'verbose_name': 'Наблюдатель',
                'verbose_name_plural': 'Наблюдатели',
            },
        ),
    ]
