# Generated by Django 5.1 on 2024-10-09 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observers', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        ('tectasks', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='date_added',
        ),
        migrations.AddField(
            model_name='observer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_observers', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_observers', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='tectask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tectask_observers', to='tectasks.tectask'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_observers', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатель'),
        ),
    ]
