# Generated by Django 5.1 on 2024-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requested_extension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('extension_requested', 'Запрос на продление'), ('done', 'Выполнена'), ('completed', 'Завершена'), ('completed_early', 'Завершена досрочно'), ('approval_pending', 'Ожидает согласования'), ('in_revision', 'Отправлена на доработку')], default='new', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
